### ISSUE TITLE
Error while creating kitchen menus.

### ISSUE THREAD

**Issue by Kauri94** [MartinRe123/Toitlustamise-valdkonna-tarkvara#46]
When user chooses a date, which is previously already used.

**Comment by marvinmaran** [comment]
closing with [commit 47](https://github.com/MartinRe123/Toitlustamise-valdkonna-tarkvara/commit/a1bf9aee98c97588494f97bf57d0221bfdefe5f1)

**Comment by marvinmaran** [comment]
wrong issue, so I reopened
